#
# Update air mail tracked configuration zones to include EU countries and change descriptions and titles.
#
#  Author Mark Brittain  
# 

UPDATE configuration SET configuration_value = CONCAT(configuration_value,', AT, BE, DE, DK, EE, ES, FI, FR, HR, HU, IE, LT, LU, LV, MT, NL, PL, PT, SE'), configuration_title = REPLACE(configuration_title,'non EU ',''), configuration_description = REPLACE(configuration_description,'non EU ','') WHERE configuration_key IN ('MODULE_SHIPPING_RMAMTLETTER_ZONES_COUNTRIES_1','MODULE_SHIPPING_RMAMTLARGELETTER_ZONES_COUNTRIES_1','MODULE_SHIPPING_RMAMTPARCEL_ZONES_COUNTRIES_1');
UPDATE configuration SET configuration_title = REPLACE(configuration_title,'non EU ','') WHERE configuration_key IN ('MODULE_SHIPPING_RMAMTLETTER_ZONES_COST0_1','MODULE_SHIPPING_RMAMTLARGELETTER_ZONES_COST0_1','MODULE_SHIPPING_RMAMTPARCEL_ZONES_COST0_1','MODULE_SHIPPING_RMAMLARGELETTER_ZONES_COST0_1','MODULE_SHIPPING_RMAMLARGELETTERSF_ZONES_COST0_1','MODULE_SHIPPING_RMAMLETTER_ZONES_COST0_1','MODULE_SHIPPING_RMAMTLETTERSF_ZONES_COST0_1','MODULE_SHIPPING_RMAMTSLARGELETTER_ZONES_COST0_1','MODULE_SHIPPING_RMAMTSLETTER_ZONES_COST0_1','MODULE_SHIPPING_RMAMTLETTER_ZONES_HANDLING_1','MODULE_SHIPPING_RMAMTLARGELETTER_ZONES_HANDLING_1','MODULE_SHIPPING_RMAMTPARCEL_ZONES_HANDLING_1');